### ISSUE TITLE
[M0-Dev]Qué es lo que hace única a cada instancia de jugador.

### ISSUE THREAD

**Issue by PabloSpiegel** [manujurado1/SportsBar-IV#10]
Voy a hacer un issue del problema que ha salido al comentar en #7. Esto es necesario para avanzar con [M0](https://github.com/manujurado1/SportsBar-IV/milestone/1)

Pusiste el comentario
> Como duda que me gustaría consultar contigo es si hacer que lo que haga única cada instancia sea el identificador o la tupla de identificador + identificador de grupo.

Y entendía que te referías a qué hace único a un jugador. En principio debería de hacer único al jugador su identificiador, ya que habrá jugadores que cambien de grupo de un partido a otro para poder cumplir con tener [partidos igualados](https://github.com/manujurado1/SportsBar-IV/issues/3)

**Comment by manujurado1** [comment]
Quizás no me he explicado bien a la hora de explicar el problema. Con grupo de juego me refiero a la totalidad de jugadores que suelen juntarse para jugar, poniendo de ejemplo las 20 personas que forman una pandilla, pero no todos participan en todos los partidos ya que no siempre estarán disponibles. Es decir, una vez que se cree un jugador, este se crea perteneciendo a un grupo de juego.

**Comment by PabloSpiegel** [comment]
Hola. Después de pensarlo varias veces, he pensado que lo mejor va a ser que lo que haga único a cada jugador sea el nombre junto al grupo en el que está, ya que no van a estar pasándose los jugadores entre grupos, un jugador no tiene sentido fuera del grupo en el que está.

**Comment by manujurado1** [comment]
Perfecto, lo veo bien. Es el grupo la clase entidad y la que maneja la clase de jugador
