### ISSUE TITLE
Las historias de usuario se deben basar en un user journey

### ISSUE THREAD

**Issue by JJ** [manujurado1/SportsBar-IV#101]
Y el user journey es una descripción del problema y del contexto. 

https://github.com/manujurado1/SportsBar-IV/blob/b22052ec8db5c3acd71842700c60f42fc4e14bde/docs/secciones/04_planificacion.tex#L10

En todo caso, las historias de usuario son una parte esencial de la metodología y deben ser usadas, por ejemplo, para crear los tests.

**Comment by manujurado1** [comment]
Buenas @JJ. ¿Ves buena idea usar aquí el mismo user journey usado en la introducción (#98) y sacar la HU de ahí y cambiarla por las existentes que realmente tienen el mismo problema? Para simplificarlo todo y poder usar la HU de mejor manera.

**Comment by JJ** [comment]
> Buenas @JJ. ¿Ves buena idea usar aquí el mismo user journey usado en la introducción (#98) y sacar la HU de ahí y cambiarla por las existentes que realmente tienen el mismo problema? Para simplificarlo todo y poder usar la HU de mejor manera.

Parece una forma razonable, pero hasta que no vea el PR es difícil saber si estamos en la misma página.
