### ISSUE TITLE
[M0-Dev]Representación del nivel

### ISSUE THREAD

**Issue by PabloSpiegel** [manujurado1/SportsBar-IV#11]
De la issue mal planteada #7 me salió la duda de cómo debería representarse el nivel de un jugador, un problema que surge de las [HU1](#3) y [HU3](#4).

Por que quede documentado, te pregunté si el nivel debería ser un entero, y el me comentó que preferiría que fuese un float, con un valor entre 1 y 10.

A mí me parece mejor idea, más flexible a la hora de cambiar niveles según el resultado del partido, por ejemplo. Si tienes algún comentario más que hacer al respecto aquí estoy.

**Comment by manujurado1** [comment]
Pienso igual que tu, veo float la mejor opción
