### ISSUE TITLE
¿En qué situaciones no se podrán crear 2 equipos igualados

### ISSUE THREAD

**Issue by manujurado1** [manujurado1/SportsBar-IV#110]
Continuando con el propósito de crear la estructura de datos adecuada para complacer la HU #107. Se necesitan saber los casos de error en los que no se podrán crear 2 equipos igualados.

**Comment by JJ** [comment]
Yo creo que en este milestone es mejor que trates sólo de errores de creación de los objetos valor. Es difícil de predecir qué errores de este tipo va a haber.
