### ISSUE TITLE
¿Qué es un "amigo"?

### ISSUE THREAD

**Issue by manujurado1** [manujurado1/SportsBar-IV#114]
Con el fin de crear una estructura de datos que nos permita complacer la HU #107, necesitamos definir que es un amigo.

En primer lugar, se necesita poder crear amigos, para que estos formen parte del grupo de amigos.

Por otra parte, necesitamos un tipo nombre que nos permita poder identificar a un amigo de otro dentro del grupo, ya que el grupo está formado por un conjunto de amigos.
La forma de identificar a un amigo tiene que ser un tipo de dato plano ya que un equipo viene dado como una lista de identificadores que indican los amigos que pertenecen a ese equipo.
También debemos ofrecer la posibilidad de consultar si un amigo está disponible o no para jugar, al igual que cambiar esta disponibilidad. Esto es debido a que la HU menciona que se harán los equipos con los amigos disponibles en ese momento.
Por último, necesitamos saber el nivel (#112) de cada jugador, ya que en función del mismo se reparten los jugadores en los 2 equipos. Además, tener la posibilidad de aumentar y disminuir dicho nivel siguiendo las restricciones del tipo de dato "Nivel".

Además, necesitamos saber si el usuario va a poder crear más de un grupo y si un amigo puede pertenecer a más de 1 grupo. Si este caso se diera, se necesita saber como funcionaría la disponibilidad.

Para satisfacer la HU #119 necesitamos un segundo identificativo que no altere la privacidad del amigo, el cuál, fusionado con el nombre, forme un identificativo único

**Comment by JJ** [comment]
¿Incorporar nuevos amigos será también necesario?
Una vez más, ¿la aplicación va a ser individual para un solo grupo de amigos? ¿Si va a ser para varios grupos, una persona puede pertenecer a varios? ¿Una vez que se establezca la disponibilidad, va a ser disponibilidad para un grupo o para varios?
Adicionalmente, ¿cómo se va a presentar la lista de amigos? ¿Cómo va a saber una persona dónde está encuadrado? Esto implica una cosa relativamente simple: cómo vamos a almacenar el nombre; si se va a presentar una lista, lo más normal es que se ordene por apellidos... 
Recuerda en todo caso el concepto de inmutabilidad, y cómo se maneja la mutabilidad. Te aconsejo que leas algún artículo sobre "código limpio", por ejemplo. 
Por otro lado, :+1: por haber creado el issue. Crear un issue es el primer paso para poder empezar a resolver los problemas que implique.

**Comment by manujurado1** [comment]
Entiendo que todas las preguntas que planteas son preguntas que también deben ir añadidas al issue ya que son dudas que surgen al leer la HU, ¿verdad?
Esta tarde corrijo la descripción del issue y empezaré a trabajar en un PMV que lo resuelva.
Gracias!
