### ISSUE TITLE
¿Qué es un equipo?

### ISSUE THREAD

**Issue by manujurado1** [manujurado1/SportsBar-IV#117]
Al leer la HU #107 y con el fin de crear una estructura de datos que permita satisfacerla nos encontramos que se utiliza el término equipo, por lo que es necesario saber qué es un equipo y por qué está formado.
Además, necesitamos saber si un equipo va a pasar por fases en las que sea "equipo tentativo" y otras "equipo definitivo" o si directamente será definitivo en el momento en que este exista.

Adicionalmente, debemos saber para que fecha se ha creado ese equipo.

**Comment by JJ** [comment]
Deberías añadir algo más que identifique la ocasión para la que se monta el equipo, como la fecha.
