### ISSUE TITLE
[M0-Dev] ¿Cómo sabemos qué jugadores estarán disponibles?

### ISSUE THREAD

**Issue by PabloSpiegel** [manujurado1/SportsBar-IV#14]
De [HU1](https://github.com/manujurado1/SportsBar-IV/issues/2) surge el problema de cómo se sabe para cada partido quién está disponible.

**Comment by JJ** [comment]
No hay ninguna HU que hable de disponibilidad. Si no la hay, mejor no mencionarlo.
