### ISSUE TITLE
[M0-Dev]¿Qué hace falta modelar de un partido?

### ISSUE THREAD

**Issue by PabloSpiegel** [manujurado1/SportsBar-IV#15]
De [HU2](https://github.com/manujurado1/SportsBar-IV/issues/3) y [HU3](https://github.com/manujurado1/SportsBar-IV/issues/4)  se ve que vamos a necesitar modelar un partido para poder ajustar los niveles de los jugadores. En un partido intervienen muchos factores así que surge el problema de decidir qué elementos de un partido son necesarios modelar para este proyecto.

**Comment by manujurado1** [comment]
Solo será necesario saber los jugadores de cada equipo y el resultado

**Comment by JJ** [comment]
#4 no está en este milestone, por lo que no habría que hacer nada en este.

**Comment by PabloSpiegel** [comment]
@manujurado1 Hola. He hecho cambios en el repositorio y a este issue convendría quitarlo del milestone y ponerle la etiqueta invalid
