### ISSUE TITLE
[M0-Dev] ¿De qué forma se determina qué jugador es mejor? 

### ISSUE THREAD

**Issue by PabloSpiegel** [manujurado1/SportsBar-IV#16]
Viendo [HU3](https://github.com/manujurado1/SportsBar-IV/issues/4) surge la duda de si hay alguna forma de saber quién es el mejor jugador de un grupo, además del nivel que tiene cada jugador.

**Comment by manujurado1** [comment]
El nivel será el que indique eso, aunque jugando con los datos se pueda sacar a posteriori estadísticas de partidos ganados, empatados o perdidos por jugador
