### ISSUE TITLE
[HU1] Javier quiere saber cuáles de sus amigos van a estar disponibles para la sesión y disfrutar de un rato con sus amigos.

### ISSUE THREAD

**Issue by manujurado1** [manujurado1/SportsBar-IV#2]
Javier quiere crear un grupo de juego con sus amigos de la infancia saber cuáles de ellos estarán disponibles para la siguiente sesión, ya que tienen una vida algo ocupada.
No importa el nivel de cada uno, ya que el fútbol es sólo la excusa para juntarse.

**Comment by JJ** [comment]
No acabo de entender muy bien dónde está aquí la lógica de negocio. Si se trata de generar al azar, eso no tiene ningún tipo de lógica de negocio.

**Comment by JJ** [comment]
1. No cierres **NUNCA** issues desde el formulario
2. No cierres **NUNCA** historias de usuario. ¿Cómo vas a implementar la lógica de negocio? Y si no vas a implementarla, ¿qué más da? 

De verdad, yo entiendo que no vayais a clase. Pero esto lo he repetido en clase prácticamente en cada una. Os agradecería que hicierais un esfuerzo por enteraros de lo que se ha dicho allí, o simplemente preguntad en el grupo de Telegram antes de hacer algo si es correcto o no.

**Comment by manujurado1** [comment]
Vale, lo siento. Daba por hecho que como todo el milestone estaba completo se podía cerrar la HU, pero si que es verdad que es un error.
Supongo que lo idóneo es pasar esa HU al siguiente milestone con tal de dejar el primero totalmente completo no?

**Comment by JJ** [comment]
> Vale, lo siento. Daba por hecho que como todo el milestone estaba completo se podía cerrar la HU, pero si que es verdad que es un error. Supongo que lo idóneo es pasar esa HU al siguiente milestone con tal de dejar el primero totalmente completo no?

Cosa que hemos repetido casi en cada clase, también.
