### ISSUE TITLE
[HU2]  Carmen y su peña de fútbol buscan tener un partido igualado para pasárselo bien

### ISSUE THREAD

**Issue by manujurado1** [manujurado1/SportsBar-IV#3]
Carmen y sus compañeras de peña, que juegan a fútbol por diversión y dónde se encuentra gente de todo tipo de nivel, quieres crear equipos igualados para que el partido esté disputado y todo el mundo pueda aprender y disfrutar.

**Comment by JJ** [comment]
No hay ni un solo issue que plantee el problema de qué significa "igualados". Sin una modelización clara del problema y conceptos claros, es imposible desarrollar y por supuesto testearlo.
