### ISSUE TITLE
Elección del lenguaje a usar.

### ISSUE THREAD

**Issue by PabloSpiegel** [manujurado1/SportsBar-IV#6]
Hola Manu. Se me ha asignado tu repositorio y estoy pensando así que voy a empezar a modelar tu problema. ¿Has pensado en qué lenguaje usar para el proyecto?

**Comment by manujurado1** [comment]
Buenas Pablo, perdona pero estuve desconectado durante el finde. He estado pensando entre hacerlo en Go o Ruby, pero creo que finalmente me decantaré por Go, así que, si por tu parte no hay ningún impedimento, tomamos ese camino.
Mucha suerte y aquí estoy para lo que necesites!

**Comment by PabloSpiegel** [comment]
Pues me parece genial, además tenía ganas de aprenderlo.
