### ISSUE TITLE
[Fix]Existen datos duplicados en la estructura de datos de la clase Grupo

### ISSUE THREAD

**Issue by manujurado1** [manujurado1/SportsBar-IV#85]
Se ha descubierto un problema con los atributos 'JugadoresDisponibilidad' y 'JugadoresNiveles' del struct 'Grupo' al tratar de cumplir las HU https://github.com/manujurado1/SportsBar-IV/issues/2 y https://github.com/manujurado1/SportsBar-IV/issues/3. El problema se debe a la lista de jugadores aparece tanto en JugadoresDisponibilidad como en JugadoresNiveles, lo que puede ocasionar casos de error si ambas listas fueran diferentes.

**Comment by JJ** [comment]
Tienes que tratar de hacer una modelización de los datos, usando domain driven design, como vimos en clase. En todo caso, este issue también tiene que estar enlazado a una HU.

**Comment by manujurado1** [comment]
Vale cerraré este issue como inválido y abriré uno nuevo. Entiendo que tengo que hacerlo como lo hice con el issue #50 verdad?

**Comment by JJ** [comment]
En este caso yo creo que es mejor reescribirlo; al fin y al cabo, lleva implícito un problema.

**Comment by manujurado1** [comment]
¿Te refieres a editar este mismo issue explicando el problema encontrado y referenciándolo a las HU correspondientes?

**Comment by JJ** [comment]
Sí, en este caso. Bueno, en casi todos; si no hay forma, cierra como "no planeado"
