### ISSUE TITLE
Criterios de modificación de nivel

### ISSUE THREAD

**Issue by manujurado1** [manujurado1/SportsBar-IV#86]
Con el fin de satisfacer la HU #4 , se necesitan establecer los criterios de modificación de nivel. Se modificarán en función del resultado y solo se verán afectados los jugadores que hayan jugado ese partido.

Queda pendiente establecer la cantidad de variación de nivel en función del resultado.

**Comment by manujurado1** [comment]
Se ha establecido como criterios de modificación los siguientes:

- Empate -> No se modifica el nivel
- Victoria/Derrota con resultado igualado -> +/- 5 niveles*
- Victoria/Derrota abultada -> +/- 10 niveles*

Un resultado se considera abultado si un equipo ha metido el doble o más goles que el otro y además la diferencia de goles entre ambos equipos es de 3 o más goles.

(*) Si no se pueden sumar/restar esa cantidad de niveles debido a sobrepasar el nivel máximo/mínimo, se modificará con la mayor cantidad de niveles posibles.

**Comment by JJ** [comment]
Primero, no debes poner la solución en el comentario, sino en el código. Segundo, el concepto de nivel tiene que salir del análisis del dominio usando DDD. Además, siempre tienes que partir de un producto mínimamente viable: usar un solo punto, por ejemplo, o algo así. Todo lo que implique puntuaciones "ad hoc" (como 5 o 10 o 3) tiene que estar muy bien justificado, o simplemente no hacerlo.

**Comment by manujurado1** [comment]
Si, lo tengo también en el código, solo que no he subido los commits aún, lo haré ahora. Y el concepto de nivel apareció y se definió en issues enteriores de un milestone anterior. Respecto al tema de las puntuaciones, el hecho de diferencias un resultado abultado de uno igualado y definir estos dos conceptos no sería justificación para añadirlo?
De todas formas, voy a subir ahora el estado actual con todos los issues del PR resuelto para obtener una corrección general del PR.
Gracias!

**Comment by JJ** [comment]
la cuestión es que tienes que intentar hacer el producto mínimo que cumple esas condiciones; usar números mágicos no es de ninguna manera mínimo. Para cumplir bien las condiciones de la historia de usuario a veces ayuda escribir los tests antes.
Quiero decir, si lo que quieres es "subir de nivel cuando se gana, bajar cuando se pierde" con incrementar en uno es suficiente. Esquemas más complejos se pueden hacer, incluyendo posiciones y demás, o cuanto tiempo se ha jugado, o cosas así, pero lo más simple es que todo el mundo parta de 0 y se suba o baje sólo uno, me parece a mi.

**Comment by manujurado1** [comment]
Vale, entiendo y me parece correcto ese enfoque. Aunque lo único que yo modificaría es que, al moveros en un sistema de 100 niveles, que la diferencia sea de +-10 para que un resultado tenga efecto en el siguiente emparejamiento.

**Comment by JJ** [comment]
¿Te das cuenta que eso es exactamente lo mismo que un sistema de 10 niveles que se mueva con +-1 y tiene menos números mágicos?

**Comment by manujurado1** [comment]
Si es lo mismo, pero la diferencia está en que se contempla un escenario donde haya +10 personas, y con un sistema de 10 niveles te obliga a que 2 personas tengan el mismo nivel cuándo ese escenario en la vida real no tiene por qué darse. De ahí el hecho de que el sistema fuera de 100 niveles.

**Comment by JJ** [comment]
De veras, haz un poco las cuentas. Si suben y bajan 10, no van a tener valores intermedios como 63 o 35. Es *exactamente igual* que si bajan y suben 1.

**Comment by manujurado1** [comment]
Ya, en ese caso es exactamente lo mismo, por eso en este issue se planteaba la idea de según el tipo de resultado sumar o restar más o menos puntos.

Pero considerando enfocarlo todo hacia un PMV, si que veo el sentido en establecer un rango de 10 niveles y modificar +-1, dejando como posibilidad mejorar la aplicación en un futuro ampliando el rango y haciendo un sistema de modificación de niveles más complejo.

Supongo que ese es el enfoque correcto, ¿cierto?

**Comment by JJ** [comment]
Es que no tienes que plantear ninguna solución, sólo los problemas. Quieres
que haya topes, por alguna razón, para solucionar algo. Quieres comparar
equipos, o construir equipos. Y así sucesivamente. A partir de ahí, se
busca la solución más simple. Ni siquiera tienes que subir o bajar de
nivel; en mi experiencia, el que es malo es malo, y el que es bueno es
bueno; tampoco estamos entrenando para las olimpiadas. Usa tu experiencia
personal en el problema, más que pensar en la implementación y en nada
complicado, al menos como primera aproximación.

**Comment by manujurado1** [comment]
Necesito que haya un nivel mínimo porque carece de sentido un nivel negativo, de ahí la solución de acotar los niveles a un rango. Luego necesito los niveles para generar los equipos igualados en función del nivel de los jugadores.

Luego, entiendo y comparto el tema de quien es bueno es bueno y quien es malo es malo. El tema de modificar niveles viene dado de que el nivel inicial es introducido por el usuario, relacionando el nivel de cada jugador con un número (por esta razón también es necesario tener un rango de niveles). Y si una vez creados los equipos igualados en función del nivel, por poner un ejemplo, el partido queda 20-0, es obvio que los niveles introducidos no hacen relación al nivel real, de ahí el actualizar niveles automáticamente para acercarse al nivel real.

Dicho esto, si que considero que la primera aproximación puede ser más simple de la que planteo.

**Comment by JJ** [comment]
Carece de sentido un nivel negativo porque ya has decidido que va a tener un valor numérico. Como te digo, no estás tratando de resolver el problema desde el principio, sino simplemente aplicando lo que ya habías hecho y tratando de meterlo como planteamiento del problema. Como te digo, tienes que centrarte en el problema en si: describir el nivel de un equipo a partir del nivel de los jugadores, y la solución más simple posible.

**Comment by manujurado1** [comment]
Si, el nivel de un equipo viene dado por la media de nivel de los jugadores que lo forman. Pero para que eso tenga un sentido, el nivel de los jugadores tiene que estar acotado, porque que el nivel sea un simple número no tiene sentido si no tiene un contexto, siendo ese contexto el nivel mínimo y máximo que puede obtener un jugador.

Quizás es que tengo una perspectiva errónea y no soy capaz de verlo de la forma correcta.

**Comment by manujurado1** [comment]
Porque para mi resolver el problema tiene el siguiente camino:
- Necesito crear 2 equipos igualados = Nivel de equipo parecido
- El nivel del equipo viene dado por la media de nivel de los jugadores que lo componen
- Como el nivel de un jugador es inicialmente un número introducido por el usuario, se necesita saber el rango de niveles disponible para que el usuario sepa lo que es un nivel alto, un nivel bajo o un nivel medio
