### ISSUE TITLE
[M2-Dev] Creación y gestión historial de partidos

### ISSUE THREAD

**Issue by manujurado1** [manujurado1/SportsBar-IV#88]
Para satisfacer la HU #4. Es necesario crear un historial donde se almacenen todos los partidos jugados, con la información de qué jugadores formaban parte de cada equipo y el resultado final.
Además, una vez finalizado un partido, se debe añadir el partido al historial. (Un partido se da por finalizado cuando se inserta el resultado y se modifican los niveles de los jugadores implicados)

**Comment by JJ** [comment]
Tienes que intentar que el título del issue no parezca una tarea, sino que indique qué problema hay y lo enuncie claramente. Por ejemplo, aquí estás asumiendo que hace falta almacenar el resultado de los partidos, cuando otras soluciones son posibles: cambiar la puntuación al final de cada partido sin almacenarlo, por ejemplo.

**Comment by manujurado1** [comment]
Entendido, he caído en el error de escribir el issue como una tarea y no como un problema. Lo marco como inválido y creo otro que esté correcto 👍
