### ISSUE TITLE
Los milestones/PMVs son herramientas efectivas para comprobar que el avance del código es correcto

### ISSUE THREAD

**Issue by JJ** [manujurado1/SportsBar-IV#96]
En el caso del [milestone 0](https://github.com/manujurado1/SportsBar-IV/milestone/1) hay una frase que dice:

> En este milestone interno se abordará la creación de un módulo compilable que defina tanto la estructura de datos que almacene los jugadores de cada grupo de juego como la que defina la estructura de datos de cada jugador.

Esto no corresponde al título del milestone, y no tengo claro que se haya hecho correctamente.

**Comment by manujurado1** [comment]
Entiendo que al no haberse hecho correctamente, tiene relación con #97. Por lo que supongo que lo mejor es quitar ese párrafo del [milestone 0](https://github.com/manujurado1/SportsBar-IV/milestone/1) y añadirlo [en este](https://github.com/manujurado1/SportsBar-IV/milestone/8). ¿Correcto?

**Comment by JJ** [comment]
> Entiendo que al no haberse hecho correctamente, tiene relación con #97. Por lo que supongo que lo mejor es quitar ese párrafo del [milestone 0](https://github.com/manujurado1/SportsBar-IV/milestone/1) y añadirlo [en este](https://github.com/manujurado1/SportsBar-IV/milestone/8). ¿Correcto?

si, parece una forma razonable de hacerlo.
